// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20221210142209_seedproductdata")]
    partial class seedproductdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Data.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 12, 7, 17, 22, 9, 163, DateTimeKind.Local).AddTicks(605),
                            Name = "Bilgisayar",
                            Price = 15000m,
                            Stock = 500
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 11, 10, 17, 22, 9, 164, DateTimeKind.Local).AddTicks(7783),
                            Name = "Telefon",
                            Price = 10000m,
                            Stock = 502
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 10, 11, 17, 22, 9, 164, DateTimeKind.Local).AddTicks(7816),
                            Name = "Klavye",
                            Price = 545m,
                            Stock = 1050
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
